# Generated by Django 4.2.6 on 2023-11-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groupmodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='note',
        ),
        migrations.AddField(
            model_name='notemodel',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.groupmodel'),
            preserve_default=False,
        ),
    ]
