# Generated by Django 4.2.6 on 2023-11-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_notemodel_usermodel_note'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notemodel',
            table='note',
        ),
    ]
